import { useEffect, useState } from 'react';
import Swal from 'sweetalert2';
import { Header } from '../components/Header';
import { cancelOrder, getMyOrders, type Order } from '../api/orderAPI';

const steps = ['CONFIRMED', 'PACKED', 'PICKED_UP', 'SHIPPING', 'DELIVERED'];
const labels = ['Đã xác nhận', 'Đã đóng gói', 'Shipper nhận đơn', 'Đang vận chuyển', 'Đã giao'];

export const MyOrdersPage = () => {
  const [orders, setOrders] = useState<Order[]>([]); const [detail, setDetail] = useState<Order | null>(null);
  const load = () => getMyOrders().then(setOrders);
  useEffect(() => { load(); }, []);
  const cancel = async (id: number) => { const r = await Swal.fire({ title: 'Hủy đơn hàng?', icon: 'warning', showCancelButton: true, confirmButtonText: 'Hủy đơn', cancelButtonText: 'Quay lại' }); if (r.isConfirmed) { await cancelOrder(id); setDetail(null); load(); } };
  return <><Header onAuthWarning={() => {}} /><main style={{ maxWidth: 1000, margin: '32px auto', padding: '0 16px', fontFamily: 'sans-serif' }}><h1>Đơn hàng của tôi</h1>{orders.map(o => <article key={o.id} style={{ padding: 20, marginBottom: 14, border: '1px solid #e2e8f0', borderRadius: 12, boxShadow: '0 2px 8px #0000000d' }}><b>Đơn hàng #{o.id}</b><span style={{ float: 'right', color: '#2563eb' }}>{o.status}</span><p style={{ margin: '8px 0 4px', color: '#64748b', fontSize: '14px' }}>Thời gian đặt: {new Date(o.createdAt).toLocaleString('vi-VN')}</p><p style={{ color: '#dc2626', fontWeight: 700 }}>{o.totalAmount.toLocaleString('vi-VN')} đ</p><button onClick={() => setDetail(o)}>Xem chi tiết</button>{o.status === 'CONFIRMED' && <button onClick={() => cancel(o.id)} style={{ marginLeft: 8, color: '#dc2626' }}>Hủy</button>}</article>)}{detail && <div style={{ position: 'fixed', inset: 0, zIndex: 80, overflow: 'auto', padding: 24, background: '#0f172a88' }}><section style={{ maxWidth: 800, margin: '20px auto', padding: 28, borderRadius: 14, background: '#fff' }}><button onClick={() => setDetail(null)} style={{ float: 'right' }}>Đóng</button><h2>Đơn hàng #{detail.id}</h2><div style={{ display: 'flex', margin: '30px 0', overflowX: 'auto' }}>{steps.map((s, i) => { const active = steps.indexOf(detail.status) >= i; return <div key={s} style={{ minWidth: 110, flex: 1, textAlign: 'center', position: 'relative', color: active ? '#2563eb' : '#94a3b8' }}>{i > 0 && <div style={{ position: 'absolute', top: 10, right: '50%', width: '100%', height: 3, background: active ? '#2563eb' : '#cbd5e1' }} />}<div style={{ width: 22, height: 22, margin: 'auto', position: 'relative', borderRadius: '50%', background: active ? '#2563eb' : '#cbd5e1', border: '3px solid white' }} /><small>{labels[i]}</small></div> })}</div><p><b>Người nhận:</b> {detail.receiverName} · {detail.receiverPhone}</p><p><b>Địa chỉ:</b> {detail.deliveryAddress}</p><p><b>Thời gian đặt:</b> {new Date(detail.createdAt).toLocaleString('vi-VN')}</p><h3>Sản phẩm</h3>{detail.items.map(item => <div key={item.id} style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '12px 0', borderBottom: '1px solid #e2e8f0' }}><img src={item.imageUrl || 'https://placehold.co/80x80?text=No+Image'} alt={item.shoeName} onError={e => { e.currentTarget.src = 'https://placehold.co/80x80?text=No+Image'; }} style={{ width: 58, height: 58, objectFit: 'cover', borderRadius: 8 }} /><div style={{ flex: 1 }}><b>{item.shoeName}</b><div style={{ color: '#64748b' }}>Số lượng: {item.quantity}</div></div><b>{(item.unitPrice * item.quantity).toLocaleString('vi-VN')} đ</b></div>)}<h3 style={{ textAlign: 'right', color: '#dc2626' }}>Tổng: {detail.totalAmount.toLocaleString('vi-VN')} đ</h3></section></div>}</main></>;
};
